// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxfMMDlcLn3LWRCxtAok3QMac1z7-_G1Q',
    appId: '1:253762938934:android:5859fe760df7b9026bd097',
    messagingSenderId: '253762938934',
    projectId: 'membertracking-e18e2',
    storageBucket: 'membertracking-e18e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjmYJyfp_3U2ghXpg7WEJLQLdbSl8V-Mk',
    appId: '1:797641144612:ios:30e1dcffc5c93ebb431bb1',
    messagingSenderId: '797641144612',
    projectId: 'trial2-28f4d',
    databaseURL: 'https://trial2-28f4d-default-rtdb.firebaseio.com',
    storageBucket: 'trial2-28f4d.appspot.com',
    androidClientId: '797641144612-lns9po7310calp9opq9i52m1bethhpk8.apps.googleusercontent.com',
    iosClientId: '797641144612-7p8tqkqot9hg8maurjdg93d9p5sh290p.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamViewNoDatabaseWindows',
  );
}